name: Failing Job
on: [workflow_dispatch, pull_request]
jobs:
  initialization:
    runs-on: ubuntu-latest
    steps:
      - name: Failing job
        run: exit 1
      - name: Second stop
      - run: Woo wee!
