name: Hacked

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: hack the planet!
        run: echo hack the planet!!!
